### ISSUE TITLE
Error while checking if topic is synchronous

### ISSUE THREAD

**Issue by avoelkl** [magepal/magento2-reindex#14]
First of all: Thanks for the module! It has been working fine so far but it seem the last version 1.1.0 introduced some troubles.

#### Expected behavior:
No error during deployment.

#### Actual behavior:

Error during `setup:db-schema:upgrade` during Deployment:

```
Module 'Magento_Amqp':
302In DataMapper.php line 133:
303
304  Error while checking if topic is synchronous
```

#### Steps to reproduce:
It took me quite long to find out why I run into this error during deployment and see where it comes from.
Finally I found the reason: The last version 1.1.0 introduced a communication.xml

Magepal content in `communication.xml`
`<topic name="magepal.reindex" request="string[]" />`

Example from `vendor/magento/module-sales-rule/etc/communication.xml`

```
    <topic name="sales_rule.codegenerator" request="Magento\SalesRule\Api\Data\CouponGenerationSpecInterface">
        <handler name="codegeneratorProcessor" type="Magento\SalesRule\Model\Coupon\Consumer" method="process" />
    </topic>
```

I believe this is the problem, however I did not do further testing and set the version to 1.0.11.
Also I had to disable redis on the staging server to get it running (?!)

From the system.log:
```
[2021-01-19 11:43:16] main.ERROR: Error while checking if topic is synchronous
#0 /var/www/magento/releases/47673/vendor/magento/framework-message-queue/Topology/Config/QueueConfigItem/DataMapper.php(95): Magento\Framework\MessageQueue\Topology\Config\QueueConfigItem\DataMapper->isSynchronousTopic('magepal.reindex')
#1 /var/www/magento/releases/47673/vendor/magento/framework-message-queue/Topology/Config/QueueConfigItem/DataMapper.php(71): Magento\Framework\MessageQueue\Topology\Config\QueueConfigItem\DataMapper->createQueueItems('magepal_reindex', 'magepal.reindex', 'db')
#2 /var/www/magento/releases/47673/vendor/magento/framework-message-queue/Topology/Config/QueueConfigItem/Iterator.php(38): Magento\Framework\MessageQueue\Topology\Config\QueueConfigItem\DataMapper->getMappedData()
#3 /var/www/magento/releases/47673/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\MessageQueue\Topology\Config\QueueConfigItem\Iterator->__construct(Object(Magento\Framework\MessageQueue\Topology\Config\QueueConfigItem\DataMapper), Object(Magento\Framework\MessageQueue\Topology\Config\QueueConfigItemFactory))
#4 /var/www/magento/releases/47673/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#5 /var/www/magento/releases/47673/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#6 /var/www/magento/releases/47673/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#7 /var/www/magento/releases/47673/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#8 /var/www/magento/releases/47673/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#9 /var/www/magento/releases/47673/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#10 /var/www/magento/releases/47673/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#11 /var/www/magento/releases/47673/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Amqp\\Se...', Array)
#12 /var/www/magento/releases/47673/setup/src/Magento/Setup/Model/Installer.php(1146): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Amqp\\Se...')
#13 /var/www/magento/releases/47673/setup/src/Magento/Setup/Model/Installer.php(1523): Magento\Setup\Model\Installer->createSchemaDataHandler('Magento\\Amqp\\Se...', 'Magento\\Framewo...')
#14 /var/www/magento/releases/47673/setup/src/Magento/Setup/Model/Installer.php(1066): Magento\Setup\Model\Installer->getSchemaDataHandler('Magento_Amqp', 'schema-recurrin...')
#15 /var/www/magento/releases/47673/setup/src/Magento/Setup/Model/Installer.php(862): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array)
#16 /var/www/magento/releases/47673/setup/src/Magento/Setup/Console/Command/DbSchemaUpgradeCommand.php(83): Magento\Setup\Model\Installer->installSchema(Array)
#17 /var/www/magento/releases/47673/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DbSchemaUpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/magento/releases/47673/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/magento/releases/47673/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DbSchemaUpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/magento/releases/47673/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/magento/releases/47673/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/magento/releases/47673/bin/magento(23): Symfony\Component\Console\Application->run()
#23 {main} [] []
```

**Comment by srenon** [comment]
@avoelkl .... Sorry to hear that you are having issues. I did a quick test on a fresh demo install and was not able to reproduce the issue.


php bin/magento -v
Magento CLI 2.3.6

php bin/magento setup:db-schema:upgrade
Module 'Magento_Store':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Directory':
Module 'Magento_Amqp':
Running schema recurring...
Module 'Magento_AmqpStore':
Module 'Magento_Config':
Module 'Magento_Theme':
Module 'Magento_Backend':
Module 'Magento_Variable':


This module has been release around 15 days now with hundreds of downloads and so far only 1 other issue to my knowledge. Give me a few to figure this out.

**Comment by mbernabeu** [comment]
I have the same problem when trying to upgrade the module to version 1.1.0

**Comment by choussamaster** [comment]
Hello can Anyone share how error was resolved please ? thx

**Comment by avoelkl** [comment]
@choussamaster back when I had this issue my problem was solved using the older version of magepal/reindex 1.0.11
